# Generated by Django 2.2.16 on 2020-11-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.IntegerField(max_length=15)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('ano', models.IntegerField(max_length=4)),
                ('modelo', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=100)),
                ('cor', models.CharField(choices=[('B', 'Branco'), ('P', 'Preto'), ('V', 'Vermelho'), ('A', 'Azul')], default='B', max_length=1)),
            ],
        ),
    ]
